# This is a sample build configuration for Gradle.
# Check our guides at https://confluence.atlassian.com/x/VYk8Lw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: wardlt/openjdk-and-sklearn

pipelines:
  default:
    - step:
        script:
          # Update the sklearn models
          - cd test-files
          - python make_models.py
          - cd ..

          # Build the software
          - ./gradlew build test jacocoTestReport coveralls
          
          # Make the documentation
          - ./gradlew javadoc
          - cd doc
          - python generate-command-autodoc.py ../javadoc
          - if [ $? -ne 0 ]; then echo "Auto-doc failed."; exit 1; fi