/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

package magpie.user.server.thrift;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-5-26")
public class Entry implements org.apache.thrift.TBase<Entry, Entry._Fields>, java.io.Serializable, Cloneable, Comparable<Entry> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Entry");

  private static final org.apache.thrift.protocol.TField NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("name", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField MEASURED_PROPERTIES_FIELD_DESC = new org.apache.thrift.protocol.TField("measured_properties", org.apache.thrift.protocol.TType.MAP, (short)2);
  private static final org.apache.thrift.protocol.TField PREDICTED_PROPERTIES_FIELD_DESC = new org.apache.thrift.protocol.TField("predicted_properties", org.apache.thrift.protocol.TType.MAP, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new EntryStandardSchemeFactory());
    schemes.put(TupleScheme.class, new EntryTupleSchemeFactory());
  }

  public String name; // required
  public Map<String,Double> measured_properties; // required
  public Map<String,Double> predicted_properties; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    NAME((short)1, "name"),
    MEASURED_PROPERTIES((short)2, "measured_properties"),
    PREDICTED_PROPERTIES((short)3, "predicted_properties");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // NAME
          return NAME;
        case 2: // MEASURED_PROPERTIES
          return MEASURED_PROPERTIES;
        case 3: // PREDICTED_PROPERTIES
          return PREDICTED_PROPERTIES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.NAME, new org.apache.thrift.meta_data.FieldMetaData("name", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MEASURED_PROPERTIES, new org.apache.thrift.meta_data.FieldMetaData("measured_properties", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    tmpMap.put(_Fields.PREDICTED_PROPERTIES, new org.apache.thrift.meta_data.FieldMetaData("predicted_properties", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.MapMetaData(org.apache.thrift.protocol.TType.MAP, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING), 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Entry.class, metaDataMap);
  }

  public Entry() {
    this.measured_properties = new HashMap<String,Double>();

    this.predicted_properties = new HashMap<String,Double>();

  }

  public Entry(
    String name,
    Map<String,Double> measured_properties,
    Map<String,Double> predicted_properties)
  {
    this();
    this.name = name;
    this.measured_properties = measured_properties;
    this.predicted_properties = predicted_properties;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Entry(Entry other) {
    if (other.isSetName()) {
      this.name = other.name;
    }
    if (other.isSetMeasured_properties()) {
      Map<String,Double> __this__measured_properties = new HashMap<String,Double>(other.measured_properties);
      this.measured_properties = __this__measured_properties;
    }
    if (other.isSetPredicted_properties()) {
      Map<String,Double> __this__predicted_properties = new HashMap<String,Double>(other.predicted_properties);
      this.predicted_properties = __this__predicted_properties;
    }
  }

  public Entry deepCopy() {
    return new Entry(this);
  }

  @Override
  public void clear() {
    this.name = null;
    this.measured_properties = new HashMap<String,Double>();

    this.predicted_properties = new HashMap<String,Double>();

  }

  public String getName() {
    return this.name;
  }

  public Entry setName(String name) {
    this.name = name;
    return this;
  }

  public void unsetName() {
    this.name = null;
  }

  /** Returns true if field name is set (has been assigned a value) and false otherwise */
  public boolean isSetName() {
    return this.name != null;
  }

  public void setNameIsSet(boolean value) {
    if (!value) {
      this.name = null;
    }
  }

  public int getMeasured_propertiesSize() {
    return (this.measured_properties == null) ? 0 : this.measured_properties.size();
  }

  public void putToMeasured_properties(String key, double val) {
    if (this.measured_properties == null) {
      this.measured_properties = new HashMap<String,Double>();
    }
    this.measured_properties.put(key, val);
  }

  public Map<String,Double> getMeasured_properties() {
    return this.measured_properties;
  }

  public Entry setMeasured_properties(Map<String,Double> measured_properties) {
    this.measured_properties = measured_properties;
    return this;
  }

  public void unsetMeasured_properties() {
    this.measured_properties = null;
  }

  /** Returns true if field measured_properties is set (has been assigned a value) and false otherwise */
  public boolean isSetMeasured_properties() {
    return this.measured_properties != null;
  }

  public void setMeasured_propertiesIsSet(boolean value) {
    if (!value) {
      this.measured_properties = null;
    }
  }

  public int getPredicted_propertiesSize() {
    return (this.predicted_properties == null) ? 0 : this.predicted_properties.size();
  }

  public void putToPredicted_properties(String key, double val) {
    if (this.predicted_properties == null) {
      this.predicted_properties = new HashMap<String,Double>();
    }
    this.predicted_properties.put(key, val);
  }

  public Map<String,Double> getPredicted_properties() {
    return this.predicted_properties;
  }

  public Entry setPredicted_properties(Map<String,Double> predicted_properties) {
    this.predicted_properties = predicted_properties;
    return this;
  }

  public void unsetPredicted_properties() {
    this.predicted_properties = null;
  }

  /** Returns true if field predicted_properties is set (has been assigned a value) and false otherwise */
  public boolean isSetPredicted_properties() {
    return this.predicted_properties != null;
  }

  public void setPredicted_propertiesIsSet(boolean value) {
    if (!value) {
      this.predicted_properties = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case NAME:
      if (value == null) {
        unsetName();
      } else {
        setName((String)value);
      }
      break;

    case MEASURED_PROPERTIES:
      if (value == null) {
        unsetMeasured_properties();
      } else {
        setMeasured_properties((Map<String,Double>)value);
      }
      break;

    case PREDICTED_PROPERTIES:
      if (value == null) {
        unsetPredicted_properties();
      } else {
        setPredicted_properties((Map<String,Double>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case NAME:
      return getName();

    case MEASURED_PROPERTIES:
      return getMeasured_properties();

    case PREDICTED_PROPERTIES:
      return getPredicted_properties();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case NAME:
      return isSetName();
    case MEASURED_PROPERTIES:
      return isSetMeasured_properties();
    case PREDICTED_PROPERTIES:
      return isSetPredicted_properties();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Entry)
      return this.equals((Entry)that);
    return false;
  }

  public boolean equals(Entry that) {
    if (that == null)
      return false;

    boolean this_present_name = true && this.isSetName();
    boolean that_present_name = true && that.isSetName();
    if (this_present_name || that_present_name) {
      if (!(this_present_name && that_present_name))
        return false;
      if (!this.name.equals(that.name))
        return false;
    }

    boolean this_present_measured_properties = true && this.isSetMeasured_properties();
    boolean that_present_measured_properties = true && that.isSetMeasured_properties();
    if (this_present_measured_properties || that_present_measured_properties) {
      if (!(this_present_measured_properties && that_present_measured_properties))
        return false;
      if (!this.measured_properties.equals(that.measured_properties))
        return false;
    }

    boolean this_present_predicted_properties = true && this.isSetPredicted_properties();
    boolean that_present_predicted_properties = true && that.isSetPredicted_properties();
    if (this_present_predicted_properties || that_present_predicted_properties) {
      if (!(this_present_predicted_properties && that_present_predicted_properties))
        return false;
      if (!this.predicted_properties.equals(that.predicted_properties))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_name = true && (isSetName());
    list.add(present_name);
    if (present_name)
      list.add(name);

    boolean present_measured_properties = true && (isSetMeasured_properties());
    list.add(present_measured_properties);
    if (present_measured_properties)
      list.add(measured_properties);

    boolean present_predicted_properties = true && (isSetPredicted_properties());
    list.add(present_predicted_properties);
    if (present_predicted_properties)
      list.add(predicted_properties);

    return list.hashCode();
  }

  @Override
  public int compareTo(Entry other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetName()).compareTo(other.isSetName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.name, other.name);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetMeasured_properties()).compareTo(other.isSetMeasured_properties());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMeasured_properties()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.measured_properties, other.measured_properties);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPredicted_properties()).compareTo(other.isSetPredicted_properties());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPredicted_properties()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.predicted_properties, other.predicted_properties);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Entry(");
    boolean first = true;

    sb.append("name:");
    if (this.name == null) {
      sb.append("null");
    } else {
      sb.append(this.name);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("measured_properties:");
    if (this.measured_properties == null) {
      sb.append("null");
    } else {
      sb.append(this.measured_properties);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("predicted_properties:");
    if (this.predicted_properties == null) {
      sb.append("null");
    } else {
      sb.append(this.predicted_properties);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class EntryStandardSchemeFactory implements SchemeFactory {
    public EntryStandardScheme getScheme() {
      return new EntryStandardScheme();
    }
  }

  private static class EntryStandardScheme extends StandardScheme<Entry> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Entry struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.name = iprot.readString();
              struct.setNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // MEASURED_PROPERTIES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map0 = iprot.readMapBegin();
                struct.measured_properties = new HashMap<String,Double>(2*_map0.size);
                String _key1;
                double _val2;
                for (int _i3 = 0; _i3 < _map0.size; ++_i3)
                {
                  _key1 = iprot.readString();
                  _val2 = iprot.readDouble();
                  struct.measured_properties.put(_key1, _val2);
                }
                iprot.readMapEnd();
              }
              struct.setMeasured_propertiesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // PREDICTED_PROPERTIES
            if (schemeField.type == org.apache.thrift.protocol.TType.MAP) {
              {
                org.apache.thrift.protocol.TMap _map4 = iprot.readMapBegin();
                struct.predicted_properties = new HashMap<String,Double>(2*_map4.size);
                String _key5;
                double _val6;
                for (int _i7 = 0; _i7 < _map4.size; ++_i7)
                {
                  _key5 = iprot.readString();
                  _val6 = iprot.readDouble();
                  struct.predicted_properties.put(_key5, _val6);
                }
                iprot.readMapEnd();
              }
              struct.setPredicted_propertiesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Entry struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.name != null) {
        oprot.writeFieldBegin(NAME_FIELD_DESC);
        oprot.writeString(struct.name);
        oprot.writeFieldEnd();
      }
      if (struct.measured_properties != null) {
        oprot.writeFieldBegin(MEASURED_PROPERTIES_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.DOUBLE, struct.measured_properties.size()));
          for (Map.Entry<String, Double> _iter8 : struct.measured_properties.entrySet())
          {
            oprot.writeString(_iter8.getKey());
            oprot.writeDouble(_iter8.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.predicted_properties != null) {
        oprot.writeFieldBegin(PREDICTED_PROPERTIES_FIELD_DESC);
        {
          oprot.writeMapBegin(new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.DOUBLE, struct.predicted_properties.size()));
          for (Map.Entry<String, Double> _iter9 : struct.predicted_properties.entrySet())
          {
            oprot.writeString(_iter9.getKey());
            oprot.writeDouble(_iter9.getValue());
          }
          oprot.writeMapEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class EntryTupleSchemeFactory implements SchemeFactory {
    public EntryTupleScheme getScheme() {
      return new EntryTupleScheme();
    }
  }

  private static class EntryTupleScheme extends TupleScheme<Entry> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Entry struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetName()) {
        optionals.set(0);
      }
      if (struct.isSetMeasured_properties()) {
        optionals.set(1);
      }
      if (struct.isSetPredicted_properties()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetName()) {
        oprot.writeString(struct.name);
      }
      if (struct.isSetMeasured_properties()) {
        {
          oprot.writeI32(struct.measured_properties.size());
          for (Map.Entry<String, Double> _iter10 : struct.measured_properties.entrySet())
          {
            oprot.writeString(_iter10.getKey());
            oprot.writeDouble(_iter10.getValue());
          }
        }
      }
      if (struct.isSetPredicted_properties()) {
        {
          oprot.writeI32(struct.predicted_properties.size());
          for (Map.Entry<String, Double> _iter11 : struct.predicted_properties.entrySet())
          {
            oprot.writeString(_iter11.getKey());
            oprot.writeDouble(_iter11.getValue());
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Entry struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.name = iprot.readString();
        struct.setNameIsSet(true);
      }
      if (incoming.get(1)) {
        {
          org.apache.thrift.protocol.TMap _map12 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.measured_properties = new HashMap<String,Double>(2*_map12.size);
          String _key13;
          double _val14;
          for (int _i15 = 0; _i15 < _map12.size; ++_i15)
          {
            _key13 = iprot.readString();
            _val14 = iprot.readDouble();
            struct.measured_properties.put(_key13, _val14);
          }
        }
        struct.setMeasured_propertiesIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TMap _map16 = new org.apache.thrift.protocol.TMap(org.apache.thrift.protocol.TType.STRING, org.apache.thrift.protocol.TType.DOUBLE, iprot.readI32());
          struct.predicted_properties = new HashMap<String,Double>(2*_map16.size);
          String _key17;
          double _val18;
          for (int _i19 = 0; _i19 < _map16.size; ++_i19)
          {
            _key17 = iprot.readString();
            _val18 = iprot.readDouble();
            struct.predicted_properties.put(_key17, _val18);
          }
        }
        struct.setPredicted_propertiesIsSet(true);
      }
    }
  }

}

