swagger: '2.0'

info:
  version: "0.0.1"
  title: Magpie REST API
  description: The REST API used to interact with models hosted by a Magpie server

paths:
  /server/version:
    get:
      description: Get the version of the REST API
      responses:
        200:
          description: Successful response

  /server/status:
    get:
      description: |
       Information about the server. Includes the versions of the software and API, available memory, and processor count
      produces:
        - application/json
      responses:
        200:
          description: Successful response

  /model/{name}/info:
    get:
      description: |
        Gets information about a model stored in the server
      parameters:
        - name: name
          in: path
          description: Name of model
          required: true
          type: number
          format: int
      produces:
        - application/json
      responses:
        200:
          description: Successful response
        404:
          description: No model by that name found

  /model/{name}/model:
    get:
      description: |
        Get the model, serialized
      parameters:
        - name: name
          in: path
          description: Name of model
          required: true
          type: number
          format: int
      produces:
        - application/octet-stream
      responses:
        200:
          description: Successful response
        404:
          description: No model by that name found

  /model/{name}/dataset:
    get:
      description: |
        Get the dataset used to generate inputs for this model, serialized
      parameters:
        - name: name
          in: path
          description: Name of model
          required: true
          type: string
      produces:
        - application/octet-stream
      responses:
        200:
          description: Successful response
        404:
          description: No model by that name found

  /model/{name}/attributes:
    put:
      description: |
        Generate the attributes which serve as input into this model
      parameters:
        - name: name
          in: path
          description: Name of model
          required: true
          type: string
        - name: entries
          in: formData
          description: |
            Entries to be processed as JSON file. Only key in JSON file is
            "data," which contains the entries to be run written as strings
          required: true
          schema:
            $ref: "#/definitions/Dataset"
      produces:
        - application/json
      responses:
        200:
          description: Successful response
          schema:
            $ref: "#/definitions/Dataset"
        405:
          description: Some problem in running the attribute generation

  /model/{name}/run:
    put:
      description: |
        Generate the attributes and run this model
      parameters:
        - name: name
          in: path
          description: Name of model
          required: true
          type: string
        - name: entries
          in: formData
          description: |
            Entries to be processed as JSON file. Only key in JSON file is
            "data," which contains the entries to be run written as strings
          type: string
          required: true
      produces:
        - application/json
      responses:
        200:
          description: Successful response
          schema:
            $ref: '$/definitions/Dataset"
        405:
          description: Some problem in running the attribute generation

  /models:
    get:
      description: |
        Get information about all models matching a certain query
      parameters:
        - name: datasetType
          in: query
          description: Dataset used by model must be this type
          type: string
          required: false
        - name: supportedDatasetType
          in: query
          description: |
            Dataset used by model must support data of this type. For example, data
            that is comptabile with a
            [CrystalStructureDataset](http://oqmd.org/static/analytics/magpie/javadoc/magpie/data/materials/CrystalStructureDataset.html)
            (i.e., has information about a crystal structure) is also compatible with a
            [CompositionDataset](http://oqmd.org/static/analytics/magpie/javadoc/magpie/data/materials/CompositionDataset.html)
          required: false
          type: string
      responses:
        200:
          description: Succesful response
        400:
          description: Some problem with

definitions:
  Dataset:
    type: object
    description: |
      Holds a collections of entries to be processed by,
      or that were generated by Magpie
    properties:
      attributes:
        type: array
        description: Names of attributes
        items:
          type: string
      entries:
        type: array
        description: Entries of this dataset
        items:
          $ref: "#/definitions/Dataset"
      property:
        type: string
        description: Name of the property being predicted
      units:
        type: string
        description: Units of the predicted property
      possibleClasses:
        type: array
        description: For a classification model, names of the possible classes
        items:
          type: string

  Entry:
    type: object
    description: |
      A single entry in a dataset
    properties:
      name:
        type: string
        description: Name of the the entry
      parsedName:
        type: string
        description: |
          Name of the entry, as generated by Magpie. Useful for determining
          whether the entry parsed correctly
      classProbabilities:
        type: array
        description: |
          Predicted probability that entry will be in each class,
          output of machine learning model
        items:
          type: number
          format: double
      predictedValue:
        description: |
          Predicted value, output of a machine learning model
        type: number
        format: double
      attributes:
        description: Attributes for this entry, input for a machine learning model
        type: array
        items:
          type: number
          format: double